import { MetricDefinition } from "./types";

// Kennzahlen, die der Collector-Adapter für Huawei OceanProtect meldet
// (siehe collector/adapters/oceanprotect.ts). key muss exakt mit dem
// {key} übereinstimmen, das der Collector an POST /api/collector/ingest sendet.
export const OCEANPROTECT_METRICS: MetricDefinition[] = [
  {
    key: "backup_success_rate",
    label: { de: "Backup-Erfolgsquote", en: "Backup Success Rate" },
    format: "percent",
    aggregation: "avg",
    section: "availability",
    trendGood: "up",
  },
  {
    key: "rpo_compliance_rate",
    label: { de: "RPO-Einhaltung", en: "RPO Compliance" },
    format: "percent",
    aggregation: "avg",
    section: "availability",
    trendGood: "up",
  },
  {
    key: "protected_capacity_tb",
    label: { de: "Geschützte Kapazität", en: "Protected Capacity" },
    unit: "TB",
    format: "tb",
    aggregation: "last",
    section: "capacity",
  },
  {
    key: "storage_pool_fill_level",
    label: { de: "Füllgrad Storage Pool", en: "Storage Pool Fill Level" },
    format: "percent",
    aggregation: "last",
    section: "capacity",
  },
  {
    key: "dedup_ratio",
    label: { de: "Deduplizierungsrate", en: "Deduplication Ratio" },
    unit: "×",
    format: "ratio",
    aggregation: "avg",
    section: "capacity",
  },
  {
    key: "system_availability",
    label: { de: "Systemverfügbarkeit", en: "System Availability" },
    format: "percent",
    aggregation: "avg",
    section: "hardware",
    trendGood: "up",
  },
  {
    key: "controller_cpu_usage_avg",
    label: { de: "Controller-CPU-Auslastung", en: "Controller CPU Usage" },
    format: "percent",
    aggregation: "avg",
    section: "hardware",
  },
  {
    key: "controller_memory_usage_avg",
    label: { de: "Controller-Speicherauslastung", en: "Controller Memory Usage" },
    format: "percent",
    aggregation: "avg",
    section: "hardware",
  },
  {
    key: "controllers_faulty",
    label: { de: "Fehlerhafte Controller", en: "Faulty Controllers" },
    format: "count",
    aggregation: "last",
    section: "hardware",
    trendGood: "down",
  },
  {
    key: "disks_faulty",
    label: { de: "Fehlerhafte Festplatten", en: "Faulty Disks" },
    format: "count",
    aggregation: "last",
    section: "hardware",
    trendGood: "down",
  },
  {
    key: "fans_faulty",
    label: { de: "Fehlerhafte Lüfter", en: "Faulty Fans" },
    format: "count",
    aggregation: "last",
    section: "hardware",
    trendGood: "down",
  },
  {
    key: "power_modules_faulty",
    label: { de: "Fehlerhafte Netzteile", en: "Faulty Power Modules" },
    format: "count",
    aggregation: "last",
    section: "hardware",
    trendGood: "down",
  },
  {
    key: "eth_ports_down",
    label: { de: "Netzwerk-Ports offline", en: "Network Ports Down" },
    format: "count",
    aggregation: "last",
    section: "hardware",
    trendGood: "down",
  },
  {
    key: "air_gap_isolation_events",
    label: { de: "Air-Gap-Isolationen ausgelöst", en: "Air-Gap Isolations Triggered" },
    format: "count",
    aggregation: "sum",
    section: "security",
  },
  {
    key: "alerts_critical",
    label: { de: "Kritische Alarme", en: "Critical Alerts" },
    format: "count",
    aggregation: "sum",
    section: "security",
    trendGood: "down",
  },
  {
    key: "alerts_warning",
    label: { de: "Warnungen", en: "Warnings" },
    format: "count",
    aggregation: "sum",
    section: "security",
    trendGood: "down",
  },
  {
    key: "incidents_count",
    label: { de: "Vorfälle bearbeitet", en: "Incidents Handled" },
    format: "count",
    aggregation: "sum",
    section: "operations",
    trendGood: "down",
  },
];
